spring:
  application:
    name: documentator

  ai:
    chat:
      client:
        observations:
          include-prompt: true
          include-completion: true
    mcp:
      client:
        sse:
          connections:
            excalidraw-mpc:
              url: ${EXCALIDRAW_MCP_URL}
              sse-endpoint: /sse
    openai:
      api-key: ${KIMI_API_KEY}
      base-url: https://api.moonshot.ai/
      chat:
        options:
          model: kimi-k2-thinking
          temperature: 0.7
github:
  token: ${GH_TOKEN}

logging:
  level:
    org:
      springframework:
        ai: DEBUG